[tool.poetry]
name = "catalog-scraper"
version = "0.1.0"
description = ""
authors = ["seth shoemaker <contact@sethshoemaker.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
